services:
  horamed:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV: ${ENV}
    ports:
      - "8000:8000"
    volumes:
      - ${ENV_VOLUME}
    env_file:
      - ${ENV_FILE}
    depends_on:
      - db
    environment:
      ENV: ${ENV}

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - horamed-db-data:/var/lib/postgresql/data

volumes:
  horamed-db-data:
